%YAML:1.0
---

# ****************************************************************************
# *****     注意：布尔型参数和整型参数不能有小数部分，浮点型参数必须有小数部分     *****
# ****************************************************************************

# 工作模式的取值如下所示：
#   March: 0
#   CollectGoldOre: 1
#   MineGoldOre: 2
#   MineSilverOre: 3
#   PickUpOre: 4
#   PickUpObstacle: 5
#   ExchangeOre: 6
#   RescueComrade: 7

# 相机的标识符(字符串)
Key: 'Exchange Camera'
# 相机的驱动文件名(字符串)
Name: '/dev/v4l/by-id/usb-Generic_USB_CAMERA_EP.20CC54K01-video-index0'

# -----     UVC相机的运行时参数     -----
RuntimeParam:
  # 是否在线运行(布尔型)；在线运行：1，离线运行：0
  IsOnline: 1
  # 是否录制视频(布尔型)；录制视频：1，不录制视频：0
  IsRecordVideo: 0
  # 更新数据帧任务的CPU内核编号(整型)；CPU内核由操作系统调度：-1，CPU内核固定：>=0
  UpdateDataCpuCore: 0
  # 录制视频流任务的CPU内核编号(整型)；CPU内核由操作系统调度：-1，CPU内核固定：>=0
  RecordVideoCpuCore: 2
  # 录制视频的帧率(浮点型)；默认为40.0
  RecordVideoFps: 20.0
  # 离线视频文件名称(字符串)
  OfflineVideoName: '/home/liyang/视频/01.avi'
  # 录像文件存储路径(字符串)，必须以“/”结尾
  RecordVideoPath: '/home/plutoli/data/'

# -----     UVC相机的模型参数     -----
ModelParam:
  # UVC相机OpenCV格式的内参矩阵
  CvIntrinsics: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [1651.763448,   0.000000000,    626.7924656,
           0.000000000,   1653.304811,    552.5738518,
           0.000000000,   0.000000000,    1.000000000]

  # UVC相机OpenCV格式的外参矩阵
  CvExtrinsics: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [1,   0,    0,    0,
           0,   1,    0,    0,
           0,   0,    1,    0,
           0,   0,    0,    1]

  # UVC相机OpenCV格式的畸变系数向量
  CvDistortions: !!opencv-matrix
    rows: 5
    cols: 1
    dt: d
    data: [-0.08867301374,    -0.9492367199,    0.006212117002,    -0.002325101984,    6.642035839]

# -----     UVC相机的硬件参数     -----
HardwareParams:
  -
    # 相机硬件参数适配的工作模式集合(整型)
    WorkModes: [0, 2, 3, 4, 5, 6, 7]
    # 帧率(浮点型)
    FrameRate: 30.0
    # 相机亮度(浮点型)
    Brightness: 0.0
    # 相机曝光类型(整型)；手动曝光：1，自动曝光：3
    ExposureType: 1
    # 相机曝光时间(浮点型)
    ExposureTime: 20.0
    # 相机增益值(浮点型)
    GainRaw: 72.0
    # 相机伽马值(浮点型)
    Gamma: 0.0
    # 相机饱和度(浮点型)
    Saturation: 0.0
    # 相机对比度(浮点型)
    Contrast: 0.0
    # 相机图像宽度(整型)
    Width: 1920
    # 相机图像高度(整型)
    Height: 1080
    # 相机硬件参数的选择状态(布尔型)；选中：1，未选中：0
    IsSelected: 1

  - # 相机硬件参数适配的工作模式集合(整型)
    WorkModes: [1]
    # 帧率(浮点型)
    FrameRate: 30.0
    # 相机亮度(浮点型)
    Brightness: 0.0
    # 相机曝光类型(整型)；手动曝光：1，自动曝光：3
    ExposureType: 1
    # 相机曝光时间(浮点型)
    ExposureTime: 20.0
    # 相机增益值(浮点型)
    GainRaw: 0.0
    # 相机伽马值(浮点型)
    Gamma: 0.0
    # 相机饱和度(浮点型)
    Saturation: 0.0
    # 相机对比度(浮点型)
    Contrast: 0.0
    # 相机图像宽度(整型)
    Width: 1920
    # 相机图像高度(整型)
    Height: 1080
    # 相机硬件参数的选择状态(布尔型)；选中：1，未选中：0
    IsSelected: 0