%YAML:1.0
---

# ****************************************************************************
# *****     注意：布尔型参数和整型参数不能有小数部分，浮点型参数必须有小数部分     *****
# ****************************************************************************

# 标准波特率的取值如下：
#   BR0: 0
#   BR50: 50
#   BR75: 75
#   BR110: 110
#   BR134: 134
#   BR150: 150
#   BR200: 200
#   BR300: 300
#   BR600: 600
#   BR1200: 1200
#   BR1800: 1800
#   BR2400: 2400
#   BR4800: 4800
#   BR9600: 9600
#   BR19200: 19200
#   BR38400: 38400
#   BR57600: 57600
#   BR115200: 115200
#   BR230400: 230400
#   BR460800: 460800
#   BR500000: 500000
#   BR576000: 576000
#   BR921600: 921600
#   BR1000000: 1000000
#   BR1152000: 1152000
#   BR1500000: 1500000
#   BR2000000: 2000000
#   BR2500000: 2500000
#   BR3000000: 3000000
#   BR3500000: 3500000
#   BR4000000: 4000000

# 串口标识符(字符串)
Key: 'ttyUSB0'
# 串口文件名称(字符串)
Name: '/dev/ttyUSB0'
# 波特率(整型)；必须指定标准波特率
BaudRate: 115200
# 数据位(整型)；Five:5; Six:6; Seven:7; Eight:8
DataBits: 8
# 停止位(整型)；One:1; Tow:2
StopBits: 1
# 校验位(整型)；None:0; Odd:1; Even:2; Mark:3; Space:4
Parity: 0
# 流控(整型)；None:0; Software:1; Hardware:2
FlowControl: 0
# 串口底层数据读取任务的CPU内核编号(整型)；CPU内核由操作系统调度：-1，CPU内核固定：>=0
ReadFromDriverCpuCore: -1
# 串口底层数据下写任务的CPU内核编号(整型)；CPU内核由操作系统调度：-1，CPU内核固定：>=0
WriteToDriverCpuCore: -1
# 读取缓冲区长度(整型)
ReadBufferSize: 1024
# 写入缓冲区长度(整型)
WriteBufferSize: 1024
# 数据帧分隔符(整型)；分隔符中的元素大小必须小于255
Separators: [221]